### PR TITLE
Feat: Added tests for orphaned tasks.

### PR DESCRIPTION
**Pull request by VinuB-Dev**
Date: 15/11/2024
Developer Name: Vignesh B S

---

## Issue Ticket Number
Closes Real-Dev-Squad/website-dashboard#888

## Description

Implemented changes in tasks api for Tracking Orphaned Tasks

- `tasks?orphaned=true` - Retrieves tasks assigned to users who have departed the Discord server.

Added test cases for the above api.

### Documentation Updated?

- [ ] Yes
- [x] No

### Under Feature Flag

- [x] Yes
- [ ] No

### Database Changes

- [ ] Yes
- [x] No

### Breaking Changes

- [ ] Yes
- [x] No

### Development Tested?

- [x] Yes
- [ ] No

## Screenshots
<details>
<summary>Screenshot 1</summary>

Screenshot 2024-11-26 at 12 11 08 PM

</details>

## Test Coverage
<details>
<summary>Screenshot 1</summary>

Tasks Unit test:
Screenshot 2024-11-27 at 5 49 07 PM

Screenshot 2024-11-27 at 5 54 16 PM

Users unit test:
Screenshot 2024-11-27 at 5 55 57 PM

Integration test:
Screenshot 2024-11-27 at 5 50 25 PM

Screenshot 2024-11-26 at 12 20 32 PM

</details>

## Additional Notes

[PRD](https://docs.google.com/document/d/1NCjJQ6RJlQGqdZyr8r2myuaWekYIoEORLr94fKRaCvo/edit?addon_store&tab=t.0#heading=h.cggvkhhvicot)
[Design Doc](https://docs.google.com/document/d/1ZYhy21DLHtTnXfKRlDH-7EVlKrMV2PyZs1_6czTozDk/edit?addon_store&tab=t.0#heading=h.cggvkhhvicot)
Have moved the updateTaskStatusToDone function to models as it was directly interacts with the database and performing operations such as updating task documents. This was also causing circular dependency issues.

### CODE REVIEW

**Review by pankajjs — CHANGES_REQUESTED** [review]
Can you update the screenshots?

**Comment by byt3quester** [comment]
Can you add the full test coverage including the files you changed not just the summary?

**Comment by VinuB-Dev** [comment]
> Can you add the full test coverage including the files you changed not just the summary?

I have added the files which I have changed. Is anything else required?

**Review by AnujChhikara — COMMENTED** [review]
LGTM
Sorry just testing ,MEGASTAR SURAJ SIR 🔥asked me to do this

**Pull request merged**
